### ISSUE TITLE
Request command not found

### ISSUE THREAD

**Issue by emirsavran** [Kira272921/faucetli#18]
Hi, thanks for this amazing project. When I run `faucetli request` I get an error says:
`›   Error: command request not found`

**Comment by 0xMukesh** [comment]
Hey! It was an issue with the version of oclif, we have just resolved it in v1.0.5. Can you give it a try and let me know?

**Comment by emirsavran** [comment]
Still doesn't work.

<img width="328" alt="Screen Shot 2022-04-20 at 20 10 36" src="https://user-images.githubusercontent.com/4889965/164285739-3ed132f5-996e-40da-9a4b-1516ecaf3f98.png">

**Comment by 0xMukesh** [comment]
@emirsavran Can I know what OS are you using?

**Comment by emirsavran** [comment]
@Kira272921 It's macOS Monterey 12.3.1, also have Intel processor.

**Comment by emirsavran** [comment]
I don't know if it will be helpful or not but I cloned the repo and run directly `bin/run` and it worked.

Edit:
I ran `yarn` to install dependencies and there was a diff in `yarn.lock`. After that I ran `yarn link` and made `bin/run` executable. now I can use without problems with repo file link.

**Comment by emirsavran** [comment]
@Kira272921 found the problem. It's the duplicated `package.json` inside `dist` directory. When I removed the file manually, it worked. I don't know the main cause of the issue though, maybe NVM / Unix environment related. I open a PR to fix this:
https://github.com/Kira272921/faucetli/pull/19
