### ISSUE TITLE
Solana support

### ISSUE THREAD

**Issue by 0xMukesh** [Kira272921/faucetli#48]
Hey! We're looking for a Solana developer to add Solana support to faucetli. Currently, faucetli supports only Polygon Mumbai and Rinkeby networks. 

#### How do I get started?

faucetli has two repositories - [Core repository](https://github.com/buidler-hub/faucetli) and [Backend repository](https://github.com/mukesh272921/faucetli-backend). We want to have a separate route (`/solana`) for Solana which would transfer the tokens to the user on devnet. You can use the [`@solana/web3.js`](https://www.npmjs.com/package/@solana/web3.js) library to build that route. You can checkout out this example script for getting a brief idea about how to build that route - https://github.com/solana-labs/solana-web3.js/blob/master/examples/send_sol.js. The `/solana` route would take in a required parameter "address" which is basically the public key of the user.

We would also need you to add a `solana` command to the CLI as well. The workflow of this command would be pretty much the same as the workflow of the `request` command. The command would first check if the user has configured their wallet address/public key. If no, then it would show up with a prompt asking for the user's wallet address/public key, and then it would use that wallet address/public key to call the `/solana` route. If yes, then it would fetch that wallet address/public key and call the `/solana` route.

If you face any kind of issues while building this feature, just ping me and I would try to reply as soon as possible.

**Comment by avneesh0612** [comment]
Added in #49
